name: micro-ROS Base Docker generation

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"

jobs:
  base_docker_generation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: humble
            branch: humble
          - ros_distribution: iron
            branch: iron
          - ros_distribution: rolling
            branch: main
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./base/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: microros/base:${{ matrix.ros_distribution }}